---
- name: Install development packages
  apt:
    name:
      - build-essential
      - python3-dev
      - python3-pip
      - python3-venv
      - libpq-dev
    state: present
  when: ansible_distribution == "Debian"

- name: Install development packages
  dnf:
    name:
      - gcc
      - make
      - python3-devel
      - python3-pip
      - python3-virtualenv
      - postgres
