# development tools

# debian packages
debian_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim


# fedora packages
fedora_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# archlinux packages
archlinux_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# rhel packages
rhel_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv

# centos packages
centos_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# freebsd packages
freebsd_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# openbsd packages
openbsd_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim
