- name: Install desktop packages
  apt:
    name:
    - "{{ debian_desktop_packages }}"
    state: present
  when: ansible_distribution == "Debian"

- name: Install desktop packages
  dnf:
    name:
    - "{{ fedora_desktop_packages }}"
    state: present
  when: ansible_distribution == "Fedora"

- name: Install desktop packages
  pacman:
    name:
    - "{{ archlinux_desktop_packages }}"
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install desktop packages
  dnf:
    name:
    - "{{ rhel_desktop_packages }}"
    state: present
  when: ansible_distribution == "RedHat"

- name: Install desktop packages
  yum:
    name:
    - "{{ centos_desktop_packages }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: Install desktop packages
  pkgng:
    name:
    - "{{ freebsd_desktop_packages }}"
    state: present
  when: ansible_distribution == "FreeBSD"

- name: Install desktop packages
  pkgin:
    name:
    - "{{ openbsd_desktop_packages }}"
    state: present
  when: ansible_distribution == "OpenBSD"
