---
# Variáveis específicas para Debian
debian_desktop_packages:
  - gnome-shell
  - gnome-tweaks
  - chrome-gnome-shell
  - gnome-shell-extension-dashtodock
  - fonts-firacode
  - flameshot
  - vlc

# Variáveis específicas para Fedora
fedora_desktop_packages:
  - gnome-shell
  - gnome-tweaks
  - chrome-gnome-shell
  - gnome-shell-extension-dashtodock
  - google-chrome-stable
  - liberation-fonts
  - flameshot
  - vlc
