# development tools

# debian packages
debian_desktop_packages:
- build-essential
- git
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common


# fedora packages
fedora_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# archlinux packages
archlinux_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# rhel packages
rhel_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv

# centos packages
centos_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# freebsd packages
freebsd_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim

# openbsd packages
openbsd_desktop_packages:
- build-essential
- git
- code
- development-tools
- gcc
- gcc-c++
- make
- python3
- python3-pip
- python3-virtualenv
- vim


ansible_user: "lobo"
custom_home: "/home/{{ ansible_user }}"


go_version: 1.20.2
go_archive_url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
go_archive_path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
go_install_dir: "/usr/local"

kind_repo: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
kind_git: "https://api.github.com/repos/kubernetes-sigs/kind"
kind_version: latest
kind_install_dir: /usr/local/bin

required_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - kubectl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io