---

- name: Install desktop packages in Debian
  apt:
    name: "{{ debian_desktop_packages }}"
    state: present
  when: ansible_distribution == "Debian"

- name: Add signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- import_tasks: "contributing/external-secrets.yaml"
  when: ansible_distribution == "Debian"
