---

- name: Install desktop packages in Fedora
  dnf:
    name: "{{ fedora_desktop_packages }}"
    state: present
  when: ansible_distribution == "Fedora"

- import_tasks: "contributing/external-secrets.yaml"
  when: ansible_distribution == "Fedora"
