# import os tasks
- import_tasks: debian.yaml
  when: ansible_distribution == "Debian"

- import_tasks: fedora.yaml
  when: ansible_distribution == "Fedora"

- import_tasks: archlinux.yaml
  when: ansible_distribution == "Archlinux"

- import_tasks: rhel.yaml
  when: ansible_distribution == "RedHat"

- import_tasks: centos.yaml
  when: ansible_distribution == "CentOS"

- import_tasks: freebsd.yaml
  when: ansible_distribution == "FreeBSD"

- import_tasks: openbsd.yaml
  when: ansible_distribution == "OpenBSD"
