- name: Install desktop packages
  apt:
    name:
      - gnome-shell
      - gnome-tweaks
      - chrome-gnome-shell
      - gnome-shell-extension-dashtodock
      - fonts-firacode
      - flameshot
      - vlc
    state: present
  when: ansible_distribution == "Debian"

- name: Install desktop packages
  dnf:
    name:
      - gnome-shell
      - gnome-tweaks
      - chrome-gnome-shell
      - gnome-shell-extension-dashtodock
      - google-chrome-stable
      - liberation-fonts
      - flameshot
      - vlc
    state: present
  when: ansible_distribution == "Fedora"

- name: Copy desktop configuration file
  template:
    src: desktop.conf.j2
    dest: /etc/desktop.conf
  become: true
  notify: restart desktop service

handlers:
  - include_tasks: handlers/main.yml
