---

- name: Download do arquivo de instalação do Go
  get_url:
    url: "{{ go_archive_url }}"
    dest: "{{ go_archive_path }}"

- name: Extrair arquivo do Go
  become: yes
  become_user: "{{ ansible_user }}"
  unarchive:
    src: "{{ go_archive_path }}"
    dest: "{{ go_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configurar variáveis de ambiente para Go
  become: yes
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "{{ custom_home }}/.profile"
    line: "export PATH=$PATH:/usr/local/go/bin"
    create: yes

- name: Configurar variáveis de ambiente para Go
  become: yes
  become_user: "{{ ansible_user }}"
  lineinfile:
    dest: "{{ custom_home }}/.profile"
    line: "export PATH=$PATH:/usr/local/go/bin"
    create: yes

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true

- name: Adicionar usuário ao grupo Docker
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes


- name: Download kind to specified location {{ kind_install_dir }}
  get_url:
    url: "{{ kind_repo }}"
    dest: "{{ kind_install_dir }}/kind"
    mode: 0755
    force: true
  become: true
  tags:
    - install

- name: Installation has been finished
  debug:
    msg: "Installation of kind version {{ kind_version }} has been finished!"
  tags:
    - install