---
- name: Instalando pre-requisitos para o External Secrets
  hosts: all
  become: yes

  vars:
    go_version: 1.20.2
    go_archive_url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    go_archive_path: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    go_install_dir: "/usr/local"

  tasks:
    - name: Download do arquivo de instalação do Go
      get_url:
        url: "{{ go_archive_url }}"
        dest: "{{ go_archive_path }}"

    - name: Extrair arquivo do Go
      become: yes
      become_user: root
      unarchive:
        src: "{{ go_archive_path }}"
        dest: "{{ go_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Configurar variáveis de ambiente para Go
      become: yes
      become_user: "{{ ansible_user }}"
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.profile"
        line: "export PATH=$PATH:/usr/local/go/bin"
        create: yes

    - name: Carregar variáveis de ambiente do Go
      become: yes
      become_user: "{{ ansible_user }}"
      shell: "source {{ ansible_env.HOME }}/.profile"

    - name: Instalar Docker
      become: yes
      command: >
        sh -c "curl -fsSL https://get.docker.com -o get-docker.sh && \
        sh get-docker.sh"

    - name: Adicionar usuário ao grupo Docker
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Instalar kind
      become: yes
      community.general.kind:
        version: v0.18.0

    - name: Criar cluster com kind
      become: yes
      community.general.kind_cluster:
        name: mycluster
        api_version: "v1.18.0"

    - name: Carregar configuração do cluster no kubeconfig
      become: yes
      become_user: "{{ ansible_user }}"
      command: "kubectl cluster-info --context kind-mycluster"
